### ISSUE TITLE
step files?

### ISSUE THREAD

**Issue by Rxswyers** [NextThingCo/PocketCHIP-Mechanical#1]
Is there any way you could put the files in .step? That file extension seems to be able to be opened by a decent amount of programs. .stl is great for printing, but I would like to add a little bar where the battery goes so it doesn't move around and then print that.

I noticed that the part that goes on the back of the C.H.I.P isn't on here either.
Great job with the project already though! I just got my PocketC.H.I.P and I love it!

**Comment by jerixboy** [comment]
Hey @Rxswyers ,

Thanks for the kind words. We've just added the STEP files in the 3D_MODEL directory. Check them out [here](https://github.com/NextThingCo/PocketCHIP-Mechanical/tree/da0489b5efd4cdf1383745d1c484cc4252c9ba4e/v1.0/3D_Model/STEP_files) . Keep us posted with your project!

-J

**Comment by Rxswyers** [comment]
Oh my, you all are beautiful. Thanks for the quick reply, I appreciate it!
